spring.application.name=kirana

# Server Port
server.port=9001

# MySQL Config
# spring.datasource.url=jdbc:mysql://localhost:3306/kirana
spring.datasource.url=jdbc:mysql://172.31.16.15:3306/kirana
spring.datasource.username=root
spring.datasource.password=hrhk

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Database Logging - Disable HikariPool logs
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# History Logging
logging.level.com.kirana.History=INFO
logging.level.com.kirana.HistoryService=INFO
logging.level.com.kirana.HistoryController=INFO

# Multipart (Image Upload)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Google Cloud Vision Credentials (Individual Keys)
google.cloud.vision.type=service_account
google.cloud.vision.project-id=kirana-vision
google.cloud.vision.private-key-id=ca5e90365070991102642610b61e15edaad90240
google.cloud.vision.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/zkxWx7+Pvg/p/qIMyY7ToObKD7BJltQ4UcbK2fHNb5PuoE0c8R18QKqlsFZyeWU3oXMM/+ZHxMC7t+q7I4IUbf0dZY4viTWoDF/4NC216Z8QajaYdO+97ZdgrBQ3fUi9Basf4uKMZDXdxk0DecoNXFPWyQlG1yUWGxsMd2yceAvUlFz5mG1ymciZnqH+Xgut1Kj0tTVKVevldLnAFYtDW1uCv7iBGM9tDnHxL+T3C7vS99NnBx8DNNwlFW9sw0flj1RgAl9do8udvOTG1NGRNoF1/+WNXXMVPHR2eafD27LJ/JDRTNmOaMGnALe+ZrCuahPO4sgmeuj5iVu8BfQ/AgMBAAECggEADyQkb5dOHnVFAVZKCZNhtIAXp+zMIEsJTrbZ6AqDZZHAzk4WOEoqZzQdpH3CnT/LBzS2Bdkvnwu/oTH4FDTN4Hn8SLVLH6KHu0/axZes4hbiqSORUsCsakRWtllvMSAxPUa0xwwckTOZ8vtj+fnDwwE+Vw7Arjhuo4uZO4cz6jgGzb/vDSX5Rh5UUHVEyCpneykJ3AOWFlD1DDnabfnSk7STdXCSjLHbMrcHh/LPvSdJDXFk9OihqmwgjtyPkq+TV/hfhFn+prLM3tgX11CtACTtHdaglKq0T5jFhfawjGDp+fqia5sPlowc3B8m3e6ZFIW1I48hkdQGjcok+z0+hQKBgQDhCxFfkZfZ/W9wmgokl/WkjGIVnk5tJtIuzunXN7kihBo0+ZCtNpDgLymeb6/0qH+mb3T5uaMUpD/OKYDX3ugUZ4EE/xknZ9czhAYX7RTvndcZOsFHyl3ifdgMmagQKTfz971+TshahchIKsciPJGB8Q57Mvn58u77iZWiy9AeHQKBgQDaMMVU41ZVc3QAnzuOn5N+x8I9+hGqhyvKF88p5UCyNAB+MbJF/Urzvb8bpzBWC6Ui74zsz+zub2VVFxyftOQU9Yvl/lclEqZwe3HWKG00q5nuvNpkftJJ/TMECzkieXzokMAN+GMJQkoOo9XgXuZHQKWEAsu6VgG6O0rZNPr9CwKBgDswYwhkzbCrBKV0DljjktsNhTq0YWI6BKwFBeHyKQJYBmCKhy/XmzErlmGydG//5VsME5Me7TKfpJx/tACTAy1ir791rNL9b89/2O5wD8KaHBnppy5PnnPUr39Y5qghfzLupOtUo0OTzkKU5b0uewLXOPzUQoUoDQ0hebbQrlNNAoGBAJqmvvewO11N/AcE1j39NZpDFJbBTQxFyu/veFMFv5mP6lmH+AhLxHiHIZIEKuqSTnY4vPaNWi6Wnoh1XUCGArQoZwSaBkKsuXQ4yzM0bFNM3kqtaU6Z5Yu0ABj5q4GYAsUE9Fvylp/VcJB35/ykxyvx0l+Da8ujco4BwMe8GbqJAoGAZZ/C8qKlT63+Z9rZfmFcjTkHKZGLpw4OqHBSiQQFbhPMiISuEb42+1Y2rNRyj5ZfrNqPC3XnxSnK8zpJgEOS/KlEvCd2qumm3oh+6O4ydGEEZQQL3b4bNmDuPCzWWBMU4cK5by+3wpzaXVQZf7lHqBD2w8mO7UL+gxtlX1ZTg70=\n-----END PRIVATE KEY-----\n
google.cloud.vision.client-email=kirana-vision-service@kirana-vision.iam.gserviceaccount.com
google.cloud.vision.client-id=101238837695051443594
google.cloud.vision.auth-uri=https://accounts.google.com/o/oauth2/auth
google.cloud.vision.token-uri=https://oauth2.googleapis.com/token
google.cloud.vision.auth-provider-x509-cert-url=https://www.googleapis.com/oauth2/v1/certs
google.cloud.vision.client-x509-cert-url=https://www.googleapis.com/robot/v1/metadata/x509/kirana-vision-service%40kirana-vision.iam.gserviceaccount.com
google.cloud.vision.universe-domain=googleapis.com